[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
num_cores = 2

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "charlie"
  args = [ "--charlie", "-lparachain=debug,runtime=debug" ]

[[parachains]]
id = 2000
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=1"

  [[parachains.collators]]
  name = "normal-collator"
  image = "{{COL_IMAGE}}"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--pvf-complexity=1", "--parachain-id=2000"]

  [[parachains.collators]]
  name = "malus-collator"
  image = "{{COL_IMAGE}}"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--pvf-complexity=1", "--parachain-id=2000", "--malus"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
